version: '3'
services:
  web:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/
    working_dir: /
    command: 
      - sh
      - -c
      - npm install && npm run start
    environment:
      - NODE_ENV=production